version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"        # "weekly"
      time: '04:00'
    open-pull-requests-limit: 5
    target-branch: master
