name: Run analysis of *.md files
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.md'
jobs:
  print-links-in-md-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Print links from *.md files
        id: print-links-md
        uses: ./.github/actions/print-links
        with:
          dir-path: './'
          file-ext: 'md'

      - name: Print the total number of found links
        run: echo "Total number of found links = ${{ steps.print-links-md.outputs.total-number }}"

#      - name: Print links from '.github/actions/print-links/README.md' file
#        id: print-links-action-readme
#        uses: ./.github/actions/print-links
#        with:
#          file-path: '.github/actions/print-links/README.md'
