name: Run analysis of *.json files
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.json'
jobs:
  print-links-in-json-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Print links from *.json files
        id: print-links-json
        uses: ./.github/actions/print-links
        with:
          dir-path: './'
          file-ext: 'json'

      - name: Print the total number of found links
        run: echo "Total number of found links = ${{ steps.print-links-json.outputs.total-number }}"
